zuma-web/src/main/java/com/zuma/web/controllers/AccountManagementController.java
package com.zuma.web.controllers;

import com.zuma.db.core.domain.Company;
import com.zuma.db.core.domain.Person;
import com.zuma.db.service.CompanyService;
import java.util.List;
import javax.faces.event.PhaseEvent;
import javax.faces.event.PhaseId;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

@Component
@Scope("session")
public class AccountManagementController extends ParentController {
    @Autowired
    protected CompanyService companyService;
    private List<Company> accountPendingList;
    private List<Company> accountExistingList;
    private String pattern = "";
    private final String currentPage = null;

    public void loadData() {
        accountPendingList = companyService.getPending();
        accountExistingList = companyService.getExisting(0,pattern);
    }

    public List<Company> getAccountPendingList() {
        return accountPendingList;
    }

    public List<Company> getAccountExistingList() {
        return accountExistingList;
    }

    public List<Person> getPersonList() {       
        return dao.get("from Person where role=0"); //TOD0: verify null
    }
    
    public String getPattern() {
        return pattern;
    }

    public void setPattern(String pattern) {
        this.pattern = pattern;
    }

    public String search() {
        accountExistingList = companyService.getExisting(0,getPattern());
        return currentPage;
    }

    public void prepareContent(PhaseEvent ev) {
        if (ev.getPhaseId() == PhaseId.RENDER_RESPONSE) {
            loadData();
        }
    }

    public String refreshPage() {
        // loadData();
        return getTargetPage();
    }
}

zuma-web/src/main/java/com/zuma/web/controllers/DebugController.java
package com.zuma.web.controllers;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Properties;

import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;

import org.apache.commons.collections.iterators.EnumerationIterator;
import org.hibernate.HibernateException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Controller;

import com.zuma.db.dao.InvalidSQLSyntaxException;
import com.zuma.db.service.GenericSQLProcessorService;

@Controller
@Scope("session")
public class DebugController {
	private static final long MEGABYTE = 1024L * 1024L;
	private static final String LINE_SEPERATOR = System
			.getProperty("line.separator");
	@Autowired
	private GenericSQLProcessorService genericSQLProcessorService;

	private String userEnteredSql = " select x.a, y.a, z.a from ( select 0 a union all select 2 union all select 3 union all select 4 union all select 5 ) x cross join  ( select 0 a union all select 2 union all select 3 union all select 4 union all select 5 ) y cross join ( select 0 a union all select 2 union all select 3 union all select 4 union all select 5 ) z order by x.a, y.a, z.a";

	private Map<String, String> debugInfoMap;

	private List<String> sqlResultStrings;

	private int sqlExecutionCount = 0;

	public Map<String, String> getDebugInfoMap() {
		if (debugInfoMap == null) {
			Map<String, String> evnKeyValueMap = new HashMap<String, String>();
			Map<String, String> variables = System.getenv();
			Properties properties = System.getProperties();

			for (Map.Entry<String, String> entry : variables.entrySet()) {
				String name = entry.getKey();
				String value = entry.getValue();
				evnKeyValueMap.put(name, value);

			}

			Enumeration<Object> propertyKeys = properties.keys();
			Iterator<Object> propertyKeyIterator = new EnumerationIterator(
					propertyKeys);
			while (propertyKeyIterator.hasNext()) {
				Object key = propertyKeyIterator.next();
				evnKeyValueMap.put(key.toString(), properties.get(key)
						.toString());
			}
			evnKeyValueMap.put(
					"total amount of memory in the Java virtual machine",
					Runtime.getRuntime().totalMemory() / MEGABYTE + "MB");
			evnKeyValueMap.put("free memory in the Java virtual machine",
					Runtime.getRuntime().freeMemory() / MEGABYTE + "MB");
			evnKeyValueMap
					.put(
							"maximum amount of memory that the Java virtual machine will attempt to use",
							Runtime.getRuntime().maxMemory() / MEGABYTE + "MB");
			debugInfoMap = evnKeyValueMap;
		}
		return debugInfoMap;
	}

	public String executeSQLAndMarkTime() throws HibernateException,
			SQLException {
		long start = System.currentTimeMillis();
		try {
			for (int i = 0; i < sqlExecutionCount; i++) {
				sqlResultStrings = genericSQLProcessorService
						.execute(getUserEnteredSql());
			}
			double totalSeconds = (System.currentTimeMillis() - start) / 1000.0;
			addFacesMessageForUI("Total time = " + totalSeconds + " sec");
		} catch (InvalidSQLSyntaxException e) {
			addFacesMessageForUI("Invalid sql");
		}
		return null;
	}

	protected void addFacesMessageForUI(String uiMessage) {
		FacesMessage facesMessage = new FacesMessage(uiMessage);
		FacesContext facesContext = FacesContext.getCurrentInstance();

		facesContext.addMessage(null, facesMessage);
	}

	public List<String> getDebugInfKeyList() {
		return new ArrayList<String>(getDebugInfoMap().keySet());
	}

	public void setDebugInfKeyList(List<String> list) {
		// not used
	}

	public String getUserEnteredSql() {
		return userEnteredSql;
	}

	public void setUserEnteredSql(String userEnteredSql) {
		this.userEnteredSql = userEnteredSql;
	}

	public List<String> getSqlResultStrings() {
		return sqlResultStrings;
	}

	public void setSqlResultStrings(List<String> sqlResultStrings) {
		this.sqlResultStrings = sqlResultStrings;
	}

	public int getSqlExecutionCount() {
		return sqlExecutionCount;
	}

	public void setSqlExecutionCount(int sqlExecutionCount) {
		this.sqlExecutionCount = sqlExecutionCount;
	}

	
}

zuma-web/src/main/java/com/zuma/web/controllers/PerformanceController.java
package com.zuma.web.controllers;

import com.zuma.db.core.domain.InventoryStartData;
import com.zuma.db.core.domain.TrackerData;
import com.zuma.web.controllers.helper.analysis.DiscountsLoader;
import com.zuma.web.controllers.helper.analysis.FBLoader;
import com.zuma.web.controllers.helper.analysis.LaborLoader;
import com.zuma.web.controllers.helper.analysis.Net2Loader;
import com.zuma.web.controllers.helper.analysis.PaperLoader;
import com.zuma.db.service.util.Week;
import java.awt.Color;
import java.awt.Font;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.io.OutputStream;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.util.Calendar;
import javax.faces.event.PhaseEvent;
import javax.faces.event.PhaseId;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;
import javax.imageio.ImageIO;
import org.apache.log4j.Logger;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.AxisLocation;
import org.jfree.chart.axis.CategoryAxis;
import org.jfree.chart.axis.NumberAxis;
import org.jfree.chart.labels.StandardCategoryItemLabelGenerator;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.category.DefaultCategoryDataset;

@Component
@Scope("session")
public class PerformanceController extends AnalysisParentController {

    public static final String foodItems = "Food Items";
    private InventoryStartData inventoryStartData;

    @Override
    public void recalculate(PhaseEvent ev) throws ParseException, Exception {
        super.recalculate(ev);
        if (ev.getPhaseId() == PhaseId.RENDER_RESPONSE) {
            String sql = "FROM InventoryStartData WHERE store.id=" + getStore().getId().toString();
            inventoryStartData = dao.getObject(sql, InventoryStartData.class);
            if (inventoryStartData == null) {
                inventoryStartData = new InventoryStartData(getStore());

            }
        }
        //  summaryController.recalculate(ev);
        //  wasteController.recalculate(ev);
        //  purchaseViewController.reInitDataList();
        //   inventoryViewController.isCopyFromPreviousWeekEnabled();
        //   prepareMaps();
    }

    public boolean isNeededStartDataDialog() {
        return getInventoryStartData().getId() == null && getStore().getRequestDate().after(Week.getCurrentWeekBegin());
    }

    public String saveInventoryStartData() {
        dao.saveOrUpdate(getInventoryStartData());
        return null;
    }

    public BigDecimal getBegInventory() {
        BigDecimal result = BigDecimal.ZERO;
        FBLoader loader = new FBLoader(dao, getStore(), getStartDate(), getFinishDate());
        try {
            Calendar date = (Calendar) getStartDate().clone();
            date.add(Calendar.DAY_OF_YEAR, -7);
            BigDecimal tmp = loader.getBeginInventory(date);
            if (tmp != null) {
                result = tmp;
            }
        } catch (ParseException ex) {
            Logger.getLogger(PerformanceController.class.getName()).error(null, ex);
        }
        return result;
    }

    public BigDecimal getEndInventory() {
        BigDecimal result = BigDecimal.ZERO;
        FBLoader loader = new FBLoader(dao, getStore(), getStartDate(), getFinishDate());
        try {
            BigDecimal tmp = loader.getEndInventory(getFinishDate());
            if (tmp != null) {
                result = tmp;
            }
        } catch (ParseException ex) {
            Logger.getLogger(PerformanceController.class.getName()).error(null, ex);
        }
        return result;
    }

    public BigDecimal getPurchase() {
        BigDecimal result = BigDecimal.ZERO;
        FBLoader loader = new FBLoader(dao, getStore(), getStartDate(), getFinishDate());
        try {
            BigDecimal tmp = loader.getPurchaseTotal(getStore(), getStartDate(), getFinishDate());
            if (tmp != null) {
                result = tmp;
            }
        } catch (ParseException ex) {
            Logger.getLogger(PerformanceController.class.getName()).error(null, ex);
        }
        return result;
    }

    public BigDecimal getWaste() {
        BigDecimal result = BigDecimal.ZERO;
        FBLoader loader = new FBLoader(dao, getStore(), getStartDate(), getFinishDate());
        try {
            BigDecimal tmp = loader.getWaste(getStartDate(), getFinishDate());
            if (tmp != null) {
                result = tmp;
            }
        } catch (ParseException ex) {
            Logger.getLogger(PerformanceController.class.getName()).error(null, ex);
        }
        return result;
    }

    public BigDecimal getLaborHours() {
        BigDecimal result = BigDecimal.ZERO;
        LaborLoader loader = new LaborLoader(dao, getStore(), getStartDate(), getFinishDate());
        try {
            BigDecimal tmp = loader.getLaborHours(getStore(), getStartDate(), getFinishDate());
            if (tmp != null) {
                result = tmp;
            }
        } catch (ParseException ex) {
            Logger.getLogger(PerformanceController.class.getName()).error(null, ex);
        }
        return result;
    }

    public BigDecimal getAverageLaborHours() {
        BigDecimal result = BigDecimal.ZERO;
        LaborLoader loader = new LaborLoader(dao, getStore(), getStartDate(), getFinishDate());
        try {
            BigDecimal tmp = loader.getLaborHours(getStore(), getStartDate(), getFinishDate());
            TrackerData data = getDataTargetMap().get("Labor");
            if (data != null && tmp != null && !tmp.equals(BigDecimal.ZERO)) {
                result = data.getActualCurrent().divide(tmp, 4, RoundingMode.HALF_UP);
            }
        } catch (ParseException ex) {
            Logger.getLogger(PerformanceController.class.getName()).error(null, ex);
        }
        return result;
    }

    public BigDecimal getPaperBegInventory() {
        BigDecimal result = BigDecimal.ZERO;

        PaperLoader loader = new PaperLoader(dao, getStore(), getStartDate(), getFinishDate());
        try {
            Calendar date = (Calendar) getStartDate().clone();
            date.add(Calendar.DAY_OF_YEAR, -7);
            BigDecimal tmp = loader.getBeginInventory(date);
            if (tmp != null) {
                result = tmp;
            }
        } catch (ParseException ex) {
            Logger.getLogger(PerformanceController.class.getName()).error(null, ex);
        }
        return result;
    }

    public BigDecimal getPaperEndInventory() {
        BigDecimal result = BigDecimal.ZERO;
        PaperLoader loader = new PaperLoader(dao, getStore(), getStartDate(), getFinishDate());
        try {
            BigDecimal tmp = loader.getEndInventory(getFinishDate());
            if (tmp != null) {
                result = tmp;
            }
        } catch (ParseException ex) {
            Logger.getLogger(PerformanceController.class.getName()).error(null, ex);
        }
        return result;
    }

    public BigDecimal getPaperPurchase() {
        BigDecimal result = BigDecimal.ZERO;
        PaperLoader loader = new PaperLoader(dao, getStore(), getStartDate(), getFinishDate());
        try {
            BigDecimal tmp = loader.getPurchaseTotal(getStore(), getStartDate(), getFinishDate());
            if (tmp != null) {
                result = tmp;
            }
        } catch (ParseException ex) {
            Logger.getLogger(PerformanceController.class.getName()).error(null, ex);
        }
        return result;
    }

    public BigDecimal getSales() {
        BigDecimal result = BigDecimal.ZERO;
        Net2Loader loader = new Net2Loader(dao, getStore(), getStartDate(), getFinishDate());
        try {
            //BigDecimal tmp = loader.getTotalFor("Sales", getStore(), getStartDate(), getFinishDate());
            BigDecimal tmp = loader.getTotalFor("", getStore(), getStartDate(), getFinishDate());
            if (tmp != null) {
                result = tmp;
            }
        } catch (ParseException ex) {
            Logger.getLogger(PerformanceController.class.getName()).error(null, ex);
        }
        return result;
    }

    public BigDecimal getDiscounts() {
        BigDecimal result = BigDecimal.ZERO;
        DiscountsLoader loader = new DiscountsLoader(dao, getStore(), getStartDate(), getFinishDate());
        try {
            BigDecimal tmp = loader.getCurrent();
            if (tmp != null) {
                result = tmp;
            }
        } catch (ParseException ex) {
            Logger.getLogger(PerformanceController.class.getName()).error(null, ex);
        }
        return result;
    }

    public BigDecimal getPercentDiscounts() {
        BigDecimal result = BigDecimal.ZERO;

        BigDecimal tmp = getSales();
        if (tmp != null && !tmp.equals(BigDecimal.ZERO)) {
            result = getDiscounts().divide(tmp, 4, RoundingMode.HALF_UP);
        }
        return result;
    }

    public void generateChart(double target, double current, double mtd, double ytd, OutputStream out) throws IOException {
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();

        dataset.addValue(target, "", "Target");
        dataset.addValue(current, "", "Active");
        dataset.addValue(mtd, "", "MTD");
        dataset.addValue(ytd, "", "YTD");
        double max = target;
        double min = target;

        if (current > max) {
            max = current;
        }
        if (mtd > max) {
            max = mtd;
        }
        if (ytd > max) {
            max = ytd;
        }
        if (current < min) {
            min = current;
        }
        if (mtd < min) {
            min = mtd;
        }
        if (ytd < min) {
            min = ytd;
        }
        double range = 1.1 * (max - min);

zuma-web/src/main/webapp/debug.jsp
<%@ page language="java"%>
<%@ taglib uri="http://java.sun.com/jsf/html" prefix="h"%>
<%@ taglib uri="http://java.sun.com/jsf/core" prefix="f"%>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
    "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
        <title>---DEBUG PAGE---</title>
        <link type="text/css" rel="stylesheet" href="css/zuma.css" />
        <link rel="stylesheet" type="text/css" href="css/inventoryview.css" />
    </head>
    <body>
        <f:view>
            <div id="inventiryViewContent" align="center"><f:subview
                    id="menuView">
                    <jsp:include page="includes/menu.jsp" />
                </f:subview> <h:form id="debugform">
                    <h:inputText label="Enter sql here" id="sqltext"
                                 value="#{debugController.userEnteredSql}" />
                    <h:inputText label="Enter Execution count" id="execcount"
                                 value="#{debugController.sqlExecutionCount}" />

                    <h:commandButton id="executsql" value="Execute sql!"
                                     action="#{debugController.executeSQLAndMarkTime}"></h:commandButton>
                    <h:messages layout="table" errorClass="message" styleClass="message" />

                    <h:dataTable value="#{debugController.sqlResultStrings}" var="row">
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="RESULT STRINGS" />
                            </f:facet>
                            <h:outputText value="#{row}" />
                        </h:column>
                    </h:dataTable>

                    <h:dataTable value="#{debugController.debugInfKeyList}" var="key">
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="Key" />
                            </f:facet>
                            <h:outputText value="#{key}" />
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="Value" />
                            </f:facet>
                            <h:outputText value="#{debugController.debugInfoMap[key]}" />
                        </h:column>
                    </h:dataTable>

                </h:form> <f:subview id="btm">
                    <jsp:include page="includes/bottom.jsp" />
                </f:subview></div>
        </f:view>
    </body>
</html>

zuma-web/src/main/webapp/index.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>

<%-- Redirected because we can't set the welcome page to a virtual URL. --%>
<c:redirect url="/signin.faces"/>

zuma-web/src/main/webapp/itemList.jsp
<%@ page language="java"%>
<%@ taglib uri="http://java.sun.com/jsf/html" prefix="h"%>
<%@ taglib uri="http://java.sun.com/jsf/core" prefix="f"%>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
"http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<style type="text/css">
.message {
	position: absolute;
	left: 536px;
}
</style>
<title>List of dictionaries</title>
</head>

<body>
<f:view>
	<h:form id="ItemList">
		<h:dataTable id="items" value="#{dictionaryController.dataModel}"
			var="item" border="1">
			<h:column>
				<f:facet name="header">
					<h:outputText value="ItemId" />

				</f:facet>
				<h:message styleClass="message" showSummary="true"
					showDetail="false" id="errors1" for="itemId" />
				<h:inputText id="itemId" value="#{item.itemId}"
					validatorMessage="itemId is too long">
					<f:validateLength maximum="20" minimum="2" />
				</h:inputText>
			</h:column>
			<h:column>
				<f:facet name="header">
					<h:outputText value="Code" />
				</f:facet>
				<h:message styleClass="message" showSummary="true"
					showDetail="false" id="errors2" for="code" />
				<h:inputText id="code" value="#{item.code}"
					validatorMessage="code is too long">
					<f:validateLength maximum="20" minimum="2" />
				</h:inputText>
			</h:column>

			<h:column>
				<f:facet name="header">
					<h:outputText value="Description" />
				</f:facet>
				<h:message styleClass="message" showSummary="true"
					showDetail="false" id="errors3" for="description" />
				<h:inputText id="description" value="#{item.description}"
					validatorMessage="description is too long">
					<f:validateLength maximum="20" minimum="2" />
				</h:inputText>

			</h:column>
			<h:column>
				<f:facet name="header">
					<h:outputText value="Delete" />
				</f:facet>
				<h:commandLink id="Delete"
					action="#{dictionaryController.deleteDictionary}">
					<h:outputText value="Delete" />
					<f:setPropertyActionListener
						target="#{dictionaryController.selectedDictionary}"
						value="#{item}" />
				</h:commandLink>
			</h:column>
		</h:dataTable>

		<h:commandButton immediate="true" id="Add"
			action="#{dictionaryController.addNewDictionary}" value="Add an item" />
		<h:commandButton id="update"
			action="#{dictionaryController.performUpdate}" value="Update" />
		<h:commandButton id="add100" value="Add100"
			action="#{dictionaryController.addDictionarys}">
			<f:setPropertyActionListener
				target="#{dictionaryController.amountToAdd}" value="100" />
		</h:commandButton>
	</h:form>
</f:view>
<a href="index.faces">Index</a>
</body>
</html>

zuma-web/src/main/webapp/reportcenter.jsp
<%@ page language="java"%>
<%@ taglib uri="http://java.sun.com/jsf/html" prefix="h"%>
<%@ taglib uri="http://java.sun.com/jsf/core" prefix="f"%>
<%@ taglib uri="http://richfaces.org/a4j" prefix="a4j"%>
<%@ taglib uri="http://richfaces.org/rich" prefix="rich"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
    "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
        <title>Report Center</title>
        <link type="text/css" rel="stylesheet" href="css/zuma.css"/>
        <style type="text/css">
            .container{
                position:relative;
                width:50%;
                height:50%;
                float:left;
            }
            .header{
                background-color: gray;
                border-left:1px white solid;
                color:white;
                font-weight:normal;
                font-size:16px;
                width:99%;
                height:20px;
                padding-left:3px;
            }
            .detail{
                width:49%;
                float:left;
            }
            .diagram{
                width:50%;
                float:right;
                border-left:solid black 1px;
                text-align: right;
            }
            td.inf, td.inf-value {height:20px;
                                  color:#666666;
                                  font-weight:normal;
            }
            td.inf-value{
                text-align:right;
            }
            .target_lnk{
                padding-right: 15px;
            }
            .invent_lnk{
                color: #666666;
            }
            input.buttonSave{
                width: 100px;
            }
            .rich-mpnl-header {
                background-image: url('images/bg_cap.jpg');
            }
            .rich-table {
                border:none;
                border-collapse:separate;
            }
            .rich-table-headercell {
                background-image: url('images/bg_cap.jpg');
                background-repeat: repeat-x;
            }
            .rich-table-cell, .rich-subtable-cell {
                padding:0px;
                text-align:left;
                vertical-align:middle;
                border:1px solid #C4C0C9;
                font-size:12px;
            }
            .editor {
                border:0px;
                width:80px;
                text-align:right;
            }
            .category-style {
                font-size:14px;
                font-weight:normal;
                color:white;
                text-align:left;
                vertical-align:middle;
                background-color:gray;
            }
            .subcategory-style {
                font-size:medium;
                font-weight:normal;
                text-align:left;
                vertical-align:middle;
                background-color:#C0C0C0;
            }
            .item-style {
                text-align:left;
                border-width:1px;
                border:0px;
            }
            .item-style-calculated {
                text-align:right;
                background-color:#F6FCF7;
                font-size:13px;
                font-weight:bold;
                border-width:1px;
                border:0px;
            }
            .message {
                position: absolute;
                right: 15%;
            }
            .spacer {
                background-color:white;
                border:none;
                height:14px;
            }

        </style>
        <script type="text/javascript" src="js/prototype.js"></script>
        <script type="text/javascript" src="js/hotkeys.js"></script>
        <script type="text/javascript" src="js/table.js"></script>
        <script type="text/javascript" src="js/effects.js"></script>
        <script type="text/javascript" src="js/messages.js"></script>
        <script type="text/javascript">
            function updateDialog()
            {
                $('dialogHeader').style.backgroundImage = "url('images/bg_cap.jpg')";
            }
        </script>
    </head>
    <body>
        <f:view beforePhase="#{performanceController.recalculate}">
            <f:subview id="flying">
                <c:import url="includes/flyingpanels.jsp" />
            </f:subview>
            <f:subview id="mnu">
                <jsp:include page="includes/menu.jsp" />
            </f:subview>
            <f:subview id="tc">
                <jsp:include page="includes/topclient.jsp" />
            </f:subview>

            <rich:modalPanel id="dialog" width="350" autosized="true"
                             showWhenRendered="#{performanceController.neededStartDataDialog}"
                             onshow='this.style.position="fixed";updateDialog();'>
                <f:facet name="header">
                    <h:panelGroup styleClass="error-header">
                        <h:outputText value="New User Information Request"></h:outputText>
                    </h:panelGroup>
                </f:facet>
                <f:facet name="controls">
                    <h:panelGroup>
                        <h:graphicImage value="/images/close.png" styleClass="hidelink" id="hideBtn"/>
                        <rich:componentControl for="dialog" attachTo="hideBtn" operation="hide" event="onclick"/>
                    </h:panelGroup>
                </f:facet>

            </rich:modalPanel>
            <h1 class="pageCaption">Report Center</h1>
            <a4j:form id="smr" ajaxSubmit="true">
                <a4j:status startStyleClass="save-sign" 
                            onstart="showSavingSign()"
                            onstop="hideSavingSign();">
                </a4j:status>

                <h:outputText style="float:left;" value="Dates" />
                <h:selectOneMenu id="datesTypeCombo" styleClass="topCombo" style="width:160px;" value="#{summaryController.dateType}" >
                    <f:selectItems value="#{summaryController.dateTypes}"/>
                    <a4j:support event="onchange" reRender="fromDateCalendar,toDateCalendar"  />
                </h:selectOneMenu>
                <h:outputText value="From" rendered="#{summaryController.fromEnabled}" />
                <rich:calendar value="#{summaryController.fromDate}" id="fromDateCalendar" locale="en" popup="true" datePattern="MM/dd/yyyy"
                               disabled="#{summaryController.dateType != 'Custom'}"       showApplyButton="false" cellWidth="24px" cellHeight="22px" style="width:200px">
                </rich:calendar>
                <h:outputText  value="To" rendered="#{summaryController.toEnabled}" />
                <rich:calendar value="#{summaryController.toDate}" id="toDateCalendar" locale="en" popup="true" datePattern="MM/dd/yyyy"
                               disabled="#{summaryController.dateType != 'Custom'}" showApplyButton="false" cellWidth="24px" cellHeight="22px" style="width:200px" rendered="#{summaryController.toEnabled}">
                </rich:calendar>
                <h:outputText value="Columns" />
                <h:selectOneMenu id="columnFrequency" styleClass="topCombo" style="width:160px;" value="#{summaryController.columnFrequency}" >
                    <f:selectItems value="#{summaryController.columnFrequencies}"/>
                </h:selectOneMenu>
                <a4j:commandButton id="save" 
                                   styleClass="buttonDisplayData"
                                   title="Display Data"
                                   reRender="smr"
                                   action="#{summaryController.displayData}" value="Display Data"
                                   >
                </a4j:commandButton>


                <rich:panel id="reports" >
                    <f:subview rendered="#{summaryController.dateType eq 'Week-to-date'}" id="weektodatereport">
                        <jsp:include page="includes/weektodatereport.jsp" />
                    </f:subview>
                    <f:subview rendered="#{summaryController.dateType eq 'Custom'}" id="customdatereport">
                        <jsp:include page="includes/customdatereport.jsp" />
                    </f:subview>
                </rich:panel>
            </a4j:form>

            <f:subview id="btm">
                <jsp:include page="includes/bottom.jsp" />
            </f:subview>
        </f:view>
    </body>
</html>